
var ie6=false;var ie7=false;var ie8=false;function setPNGSrc(img_id,img_src){if(typeof img_id=='string'||typeof img_id=='number')var image=document.getElementById(img_id);else var image=img_id;if(navigator.appVersion.indexOf("MSIE")!=-1){var arVersion=navigator.appVersion.split("MSIE");var version=parseFloat(arVersion[1]);if(version>=5.5&&version<7){try{image.src="/media/gfx/blank.gif";image.runtimeStyle.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+
img_src+"',sizingMethod='scale')";return;}catch(error){}}}else if(navigator.appVersion.indexOf("WebKit")!=-1){try{image.src="/media/gfx/blank.gif";}catch(error){}}
image.src=img_src;}
function alphaBg(elem){if(typeof elem=='string'||typeof elem=='number')elem=document.getElementById(elem);if(navigator.appVersion.indexOf("MSIE")!=-1){var arVersion=navigator.appVersion.split("MSIE");var version=parseFloat(arVersion[1]);if(version>=5.5&&version<7){if(elem.currentStyle){var y=elem.currentStyle['backgroundImage'];var attachment=elem.currentStyle['backgroundAttachment'];var repeat=elem.currentStyle['backgroundRepeat'];var position=elem.currentStyle['backgroundPosition'];var positionX=elem.currentStyle['backgroundPositionX'];var positionY=elem.currentStyle['backgroundPositionY'];}
else if(window.getComputedStyle){var y=document.defaultView.getComputedStyle(elem,null).getPropertyValue('backgroundImage');var attachment=document.defaultView.getComputedStyle(elem,null).getPropertyValue('backgroundAttachment');var repeat=document.defaultView.getComputedStyle(elem,null).getPropertyValue('backgroundRepeat');var position=document.defaultView.getComputedStyle(elem,null).getPropertyValue('backgroundPosition');var positionX=document.defaultView.getComputedStyle(elem,null).getPropertyValue('backgroundPositionX');var positionY=document.defaultView.getComputedStyle(elem,null).getPropertyValue('backgroundPositionY');}
if(y==''||y=='undefined'||y=='none'||y==null)return;y=y.substring(5,y.length-2);if(y.substring(y.length-3)!='png')return;if(typeof ookRepeat=='undefined')ookRepeat={};if(!ookRepeat[repeat])ookRepeat[repeat]=0;++ookRepeat[repeat];try{elem.style.backgroundImage="url(/media/gfx/blank.gif)";elem.runtimeStyle.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+
y+"',sizingMethod='"+(repeat=='no-repeat'?'crop':'scale')+"')";return;}catch(error){}}}}
function setPNGBackground(el_id,img_src){if(typeof el_id=='string'||typeof el_id=='number')var elem=document.getElementById(el_id);else var elem=el_id;var attachment='none';var repeat='no-repeat';if(navigator.appVersion.indexOf("MSIE")!=-1){var arVersion=navigator.appVersion.split("MSIE");var version=parseFloat(arVersion[1]);if(version>=5.5&&version<7){try{elem.style.backgroundImage="url(/media/gfx/blank.gif)";elem.runtimeStyle.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+
img_src+"',sizingMethod='crop')";return;}catch(error){}}}else if(navigator.appVersion.indexOf("WebKit")!=-1){try{elem.style.backgroundImage="url(/media/gfx/blank.gif)";}catch(error){}}
elem.style.backgroundImage="url("+img_src+")";}